# Generated by Django 5.0.6 on 2024-06-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_fecha_nacimiento_usuario_numero_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(null=True, upload_to='equipos/'),
        ),
        migrations.AlterField(
            model_name='polera',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
