# Generated by Django 5.0.6 on 2024-06-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_carrito_item_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
