# Generated by Django 5.0.6 on 2024-06-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.envio'),
        ),
    ]
