# Generated by Django 5.0.6 on 2024-07-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_compra_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
