# Generated by Django 5.0.6 on 2024-07-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_itemcarrito_comprado_alter_itemcarrito_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
    ]
