# Generated by Django 5.0.6 on 2024-07-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_itemcarrito_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='items',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.carrito'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.compra')),
                ('item_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemcarrito')),
            ],
        ),
    ]
