# Generated by Django 5.0.6 on 2024-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
