# Generated by Django 5.0.6 on 2024-07-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_usuario_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_bloqueo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
